[#chapter01-introduction]
= Introdução

Bem-vindo à API do Rails 6, um tutorial sobre esteróides para ensinar a melhor maneira de criar sua próxima API com o Rails. O objetivo deste livro é fornecer uma metodologia abrangente para o desenvolvimento de uma API RESTful seguindo as práticas recomendadas.

No final deste livro, você poderá criar sua própria API e integrá-la a qualquer cliente, como um navegador da Web ou aplicativo móvel. O código gerado é construído com o Ruby on Rails 6.0, que é a versão atual.

O objetivo deste livro não é apenas ensinar como criar uma API com o Rails, mas muito melhor, ensiná-lo a criar uma API *evolutiva* e *sustentável* com o Rails. Ou seja, melhore seu conhecimento atual com o Rails. Nesta seção, você aprenderá a:

- Usar Git para controle de versões
- Construir respostas JSON
- Testar seus end-points com testes unitários e funcionais
- Configurar autenticação com JSON Web Tokens (JWT)
- Usar a especificação JSON:API
- Otimizar a API e cache

Eu recomendo fortemente que você siga todas as etapas deste livro. Tente não pular capítulos, porque eu dou algumas dicas e truques para melhorar suas habilidades através do livro. Você pode se considerar o personagem principal de um videogame que ganha um nível em cada capítulo.

Neste primeiro capítulo, explicarei como configurar seu ambiente de desenvolvimento (caso você ainda não o conheça). Então vamos criar um aplicativo chamado `market_place_api`. Vou me certificar de ensinar as melhores práticas que aprendi durante minha experiência. Isso significa que começaremos a usar o *Git* logo após a inicialização do projeto.

Criaremos o aplicativo seguindo um método de trabalho simples que eu use diariamente nos próximos capítulos. Vamos desenvolver toda a aplicação usando o Test Driven Development (TDD). Também vou explicar o interesse de usar uma API para o seu próximo projeto e escolher uma resposta adequada em formatos como JSON ou XML. Mais adiante, colocaremos nossas mãos no código e concluiremos os conceitos básicos do aplicativo, construindo todos os caminhos necessários. Também protegeremos o acesso à API, criando autenticação, trocando cabeçalhos HTTP. Finalmente, no último capítulo, adicionaremos algumas técnicas de otimização para melhorar a estrutura e os tempos de resposta do servidor.

O aplicativo final irá percorrer a superfície de iniciar uma loja onde os usuários podem fazer pedidos, fazer envio de produtos e muito mais. Existem muitas opções por aí para iniciar uma loja online, como http://shopify.com[Shopify], http://spreecommerce.com/[Spree] o http://magento.com[Magento].

== Convenções neste livro

As convenções deste livro são baseadas neste http://www.railstutorial.org/book/beginning#sec-conventions[Tutorial de Ruby on Rails]. Nesta seção, mencionaremos alguns que talvez não sejam muito claros.

Vou usar muitos exemplos usando a linha de comando. Eu não vou usar o Windows `cmd` (desculpe pessoal), então vou basear todos os exemplos usando o estilo Unix, como mostrado abaixo:

[source,bash]
----
$ echo "A command-line command"
A command-line command
----

Vou usar algumas diretrizes relacionadas ao idioma e quero dizer o seguinte:

* *Evitar* significa que você não deve fazê-lo
* *Preferir* indica que há 2 opções, a primeira é melhor
* *Usar* significa que você pode usar o recurso

Se, por algum motivo, você encontrar alguns erros ao executar um comando, em vez de tentar explicar todos os resultados possíveis, vou recomendo que você pesquise no Google, o que não considero uma prática ruim ou qualquer que seja. Mas se você quiser tomar uma cerveja ou tiver problemas com o tutorial você sempre pode mailto:contact@rousseau-alexandre.fr[escrever-me].

== Ambientes de desenvolvimento

A configuração do ambiente de desenvolvimento é uma das partes mais dolorosas para quase todos os desenvolvedores, mas contanto que você faça isso, as etapas a seguir podem ser um pedaço do bolo e uma boa recompensa. Então, eu vou guiá-lo para que você se sinta motivado.

=== Editores de texto e terminal

Existem muitos casos em que os ambientes de desenvolvimento podem diferir de computador para computador. Este não é o caso de editores de texto ou IDE. Eu acho que para o desenvolvimento no Rails um IDE é muito, mas alguém poderia encontrá-lo como a melhor maneira de fazê-lo, portanto, se este for o seu caso, recomendo que você faça isso com http://www.aptana.com/products/radrails[RadRails] o http://www.jetbrains.com/ruby/index.html[RubyMine], ambos são bem suportados e vêm com muitas integrações 'prontas para uso'.

*Editor de texto*: Pessoalmente, eu uso http://www.vim.org/[vim] como meu editor padrão com https://github.com/carlhuda/janus[janus], que pode adicionar e gerenciar muitos dos plugins que você provavelmente vai usar. Caso você não seja fã do _vim_ como eu, existem muitas outras soluções, como http://www.sublimetext.com/[Sublime Text], que são multiplataforma, fáceis de aprender e personalizáveis ​​(essa é provavelmente a sua melhor opção), É altamente inspirado em http://macromates.com/[TextMate] (disponível apenas para Mac OS). Uma terceira opção é usar um editor de texto muito recente dos caras do http://gitub.com[GitHub] chamado https://atom.io/[Atom], é um editor de texto promissor feito com JavaScript, é fácil para estender e personalizar para atender às suas necessidades, experimente. Qualquer um dos editores que apresento a você fará o trabalho, por isso deixo que você escolha qual se encaixa nos seus olhos.

*Terminal*: Se você decidir continuar com http://icalialabs.github.io/kaishi/[kaishi] para configurar o ambiente, você notará que o padrão é o shell com `zsh`, o que eu recomendo. Para o terminal, eu não sou fã de aplicativos _Terminal_ que trazem melhorias se você estiver no Mac OS; consulte http://www.iterm2.com/#/section/home[iTerm2], que substitui o terminal em Mac OS. Se você estiver no Linux, provavelmente já possui um terminal agradável, mas o que vem por padrão pode funcionar bem.

=== Navegadores

Quando se trata de navegadores, eu diria http://www.mozilla.org/en-US/firefox/new/[Firefox] imediatamente, mas alguns outros desenvolvedores podem dizer https://www.google.com/intl/en/chrome/browser/[Chrome] ou até https://www.apple.com/safari/[Safari]. Qualquer um deles ajudará a criar o aplicativo que você está procurando, eles vêm com um bom inspetor, não apenas para o DOM, mas para análise de rede e muitos outros recursos que você já conhece.

=== Gerenciador de pacotes

* *Mac OS*: existem muitas opções para gerenciar ou instalar seus pacotes no Mac, como https://www.macports.org/[Mac Ports] ou http://brew.sh/[Homebrew], ambos são boas opções, mas eu escolheria a última, encontrei menos problemas ao instalar e gerenciar softwares. Para instalar o `brew`, basta executar o seguinte no console:

[source,bash]
----
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
----

* *Linux*: Você está pronto! Realmente não é um grande problema se você estiver usando `apt`, `pacman`, `yum` desde que se sinta confortável com algum deles, você sabe como instalar pacotes para poder continuar.

=== Git

Usaremos o Git um pouco, e você pode usá-lo não apenas para os fins deste tutorial, mas para cada projeto separado.

* no Mac OS: `$ brew install git`
* no Linux: `$ sudo apt-get install git`

=== Ruby

Existem várias maneiras de instalar e gerenciar ruby, e agora você provavelmente pode ter alguma versão instalada se estiver no Mac OS, para ver a versão que possui, basta executar:

[source,bash]
----
$ ruby -v
----

O Rails 6.0 requer a instalação da versão 2.5 ou superior.

Eu recomendo usar o http://rvm.io/[Ruby Version Manager (RVM)] ou http://rbenv.org/[rbenv] para instalá-lo. Vamos usar o RVM neste tutorial, mas não há nenhum problema com qual dos 2 você usa.

O princípio desta ferramenta é permitir que você instale várias versões do Ruby no mesmo computador, em um ambiente hermético com uma possível versão instalada no sistema operacional e, em seguida, tenha a capacidade de alternar de uma versão para outra facilmente.

Para instalar o RVM, vá para https://rvm.io/ e instale a chave GPG: [A chave GPG permite verificar a identidade do autor ou a origem do download.]. Para fazer isso, executamos:

[source,bash]
----
$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
$ \curl -sSL https://get.rvm.io | bash
----

Em seguida, é hora de instalar o ruby

[source,bash]
----
$ rvm install 2.6
----

Agora é hora de instalar o restante das dependências que vamos usar.

==== Gems, Rails e Bibliotecas ausentes


Primeiro, atualizamos as gemas no sistema:

[source,bash]
----
$ gem update --system
----

Em alguns casos, se você estiver no Mac OS, precisará instalar algumas bibliotecas extras:

[source,bash]
----
$ brew install libtool libxslt libksba openssl
----

Em seguida, instalamos as gems necessárias e ignoramos a documentação de cada uma:

Execute o comando a baixo para ignorar as documentações.

[source,bash]
$ echo 'gem: --no-rdoc --no-ri' >> ~/.gemrc

E aqui, para instalar.

[source,bash]
----
$ gem install bundler
$ gem install rails -v 6.0.0
----


Verifique se tudo está funcionando bem:

[source,bash]
----
$ rails -v
Rails 6.0.0
----

==== Base de dados

Eu recomendo que você instale http://www.postgresql.org/[Postgresql] para gerenciar seus bancos de dados. Mas aqui vamos usar o http://www.sqlite.org/[SQlite] para simplificar. Se você estiver usando o Mac OS, está pronto para continuar; caso use o Linux, não se preocupe, precisamos apenas de mais algumas etapas:

[source,bash]
----
$ sudo apt-get install libxslt-dev libxml2-dev libsqlite3-dev
----

ou

[source,bash]
----
$ sudo yum install libxslt-devel libxml2-devel libsqlite3-devel
----

== Inicializando o projeto

A inicialização de um aplicativo Rails pode ser muito fácil para você. Caso contrário, aqui está um tutorial super rápido.

Estes são os comandos:

[source,bash]
----
$ mkdir ~/workspace
$ cd ~/workspace
$ rails new market_place_api --api
----

NOTE: A opção `--api` apareceu na versão 5 do Rails. Isso permite limitar as bibliotecas e o _Middleware_ incluídos no aplicativo. Isso também evita gerar visualizações HTML ao usar geradores Rails.

Como você pode adivinhar, os comandos anteriores irão gerar a base do seu aplicativo Rails.

== Versionamento

Lembre-se de que o Git ajuda a rastrear e manter o histórico do seu código. Lembre-se de que o código fonte do aplicativo é publicado no GitHub. Você pode acompanhar o projeto em https://github.com/madeindjs/api_on_rails_6[GitHub].

O Ruby on Rails inicializa o diretório Git para você quando você usa o comando `rails new`. Isso significa que você não precisa executar o comando `git init`.

No entanto, é necessário configurar as informações do autor dos _commits_. Se você ainda não o fez, acesse o diretório do projeto e execute os seguintes comandos:

[source,bash]
----
$ git config --global user.name "Coloque seu nome aqui"
$ git config --global user.email "Coloque aqui o seu email"
----

O Rails também fornece um arquivo _.gitignore_ para ignorar alguns arquivos que não queremos rastrear. O arquivo _.gitignore_ padrão pode parecer com o seguinte:

..gitignore
----
# Ignore bundler config.
/.bundle

# Ignore the default SQLite database.
/db/*.sqlite3
/db/*.sqlite3-journal

# Ignore all logfiles and tempfiles.
/log/*
/tmp/*
!/log/.keep
!/tmp/.keep

# Ignore uploaded files in development.
/storage/*
!/storage/.keep
.byebug_history

# Ignore master key for decrypting credentials and more.
/config/master.key
----

Após modificar o arquivo _.gitignore_, precisamos apenas adicionar os arquivos e _commitar_ as alterações, para isso usamos os seguintes comandos:

[source,bash]
----
$ git add .
$ git commit -m "Commit Inicial"
----

TIP: Descobri que a mensagem de confirmação deve começar com um verbo no tempo presente, descrevendo o que o commit faz e não o que fez; isso ajuda quando você está explorando o histórico do projeto. Achei isso mais natural de ler e entender. Continuaremos esta prática até o final do tutorial.

Finalmente e como uma etapa opcional, configuramos o projeto no GitHub e fazemos _push_ do nosso código no servidor remoto: Mas primeiro adicionamos o _remote_:

[source,bash]
----
$ git remote add origin git@github.com:madeindjs/market_place_api_6.git
----

Em seguida, executamos o _push_:

[source,bash]
----
$ git push -u origin master
----

À medida que avançamos no tutorial, usarei as práticas que uso diariamente, isso inclui trabalhar com `branches`, `rebasing`, `squash` e outras coisas. Por enquanto, você não deve se preocupar se alguns desses termos não lhe parecerem familiares, eu explicarei com o tempo.

== Conclusão

Foi um longo caminho neste capítulo, se você chegou até aqui, deixe-me parabenizá-lo e garantir que as coisas melhorarão a partir deste momento. Então, vamos sujar as mãos e começar a escrever código!
