[#chapter00-before]
= Índice

== Prefácio

"API on Rails 6" é baseada em http://apionrails.icalialabs.com/book/["APIs on Rails: Building REST APIs with Rails"]. Foi publicada inicialmente em 2014 por https://twitter.com/kurenn[Abraham Kuri] sob a licença http://opensource.org/licenses/MIT[MIT] e http://people.freebsd.org/~phk/[Beerware].

A primeira versão não é mantida e foi planejada para o Ruby on Rails 4, que não https://guides.rubyonrails.org/maintenance_policy.html#security-issues[recebe mais atualizações de segurança]. Procurei atualizar este excelente livro, adaptando-o às novas versões do Ruby on Rails. Portanto, este livro está disponível para Ruby on Rails nas versões 5.2 e 6.0 (que você está lendo).

NOTE: Este livro também está disponível no idioma Molière (isso significa francês).

== Sobre o autor

Meu nome é http://rousseau-alexandre.fr[Alexandre Rousseau] e sou desenvolvedor Rails com mais de 4 anos de experiência (na data de publicação). Atualmente sou sócio em uma empresa (https://isignif.fr[iSignif]) onde construo e mantenho um produto SAAS usando Rails. Também contribuo para comunidade Ruby produzindo e mantendo algumas gemas que você pode consultar em https://rubygems.org/profiles/madeindjs[meu Rubygems.org profile]. A maioria dos meus projetos estão no GitHub, então não hesite em http://github.com/madeindjs/[seguir-me].

Todo o código fonte deste livro está no formato https://asciidoctor.org/[Asciidoctor] disponível em https://github.com/madeindjs/api_on_rails[GitHub]. Portanto, fique à vontade para fazer um https://github.com/madeindjs/api_on_rails/fork[fork] no projeto, se você quiser melhorá-lo ou corrigir bugs que eu não notei.

== Direitos autorais e licença

Este livro está sob a http://opensource.org/licenses/MIT[licença MIT]. Todo o código fonte do livro está no formato https://fr.wikipedia.org/wiki/Markdown[Markdown] disponível em https://github.com/madeindjs/api_on_rails[GitHub]

.Licença MIT
****
Copyright 2019 Alexandre Rousseau

A permissão é concedida, gratuitamente, a qualquer pessoa que obtenha uma cópia deste software e dos arquivos de documentação associados (o "Software"), para usar o Software sem restrições, incluindo, sem limitação, os direitos de uso, copiar, modificar, mesclar, publicar, distribuir, sublicenciar e / ou vender cópias do Software, e permitir que as pessoas a quem o Software é fornecido façam o mesmo, sujeito às seguintes condições:

O aviso de direitos autorais acima e este aviso de permissão serão incluídos em todas as cópias ou partes substanciais do Software.
O SOFTWARE É FORNECIDO "TAL COMO ESTÁ" SEM GARANTIA DE QUALQUER TIPO, EXPRESSA OU IMPLÍCITA, INCLUINDO, MAS NÃO SE LIMITANDO A, GARANTIAS DE COMERCIALIZAÇÃO, ADEQUAÇÃO A UMA FINALIDADE ESPECÍFICA E QUEBRA. EM NENHUM CASO OS AUTORES OU PROPRIETÁRIOS DE DIREITOS AUTORAIS SERÃO RESPONSÁVEIS POR QUALQUER REIVINDICAÇÃO, DANO OU OUTRA RESPONSABILIDADE, SEJA EM AÇÃO DE CONTRATO, TORT OU QUALQUER OUTRA RAZÃO, DERIVADA DE, FORA DE OU EM CONEXÃO COM O SOFTWARE USO OU OUTRO TIPO DE AÇÃO NO SOFTWARE.
****

"API on Rails 6" por https://github.com/madeindjs/api_on_rails[Alexandre Rousseau] é compartilhado de acordo com http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution - Attribution-ShareAlike 4.0 International]. Construído neste livro http://apionrails.icalialabs.com/book/.

A capa deste livro usa uma bela foto tirada por https://unsplash.com/@siloine?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText[Yoann Siloine] que publicou em https://unsplash.com[Unsplash].

== Agradecimentos

Um grande "obrigado" a todos os colaboradores do GitHub que mantêm este livro vivo. Em ordem alfabética:

* https://github.com/airdry[airdry]
* https://github.com/joathan[joathan]
* https://github.com/Landris18[Landris18]
* https://github.com/lex111[lex111]
* https://github.com/cuilei5205189[cuilei5205189]
* https://github.com/franklinjosmell[franklinjosmell]
* https://github.com/notapatch[notapatch]
* https://github.com/tacataca[tacataca]
